version: "3.9"
services:
  messenger-server:
    image: "messenger-server:latest"
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:8080/actuator/health" ]
      interval: 1s
      timeout: 3s
      retries: 5
  messenger-client-1:
    image: "messenger-client:latest"
    depends_on:
      messenger-server:
        condition: service_healthy
    links:
      - "messenger-server:server"
  messenger-client-2:
    image: "messenger-client:latest"
    depends_on:
      messenger-server:
        condition: service_healthy
    links:
      - "messenger-server:server"