version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - "9990:8080"
      - "9991:8443"
    command:
      - start-dev