server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9990/realms/messenger
logging:
  level:
    com.github.apsyvenko.server.web: INFO